apiVersion: apps/v1
kind: Deployment
metadata:
  name: comedy-backend
  namespace: comedy-discovery
spec:
  replicas: 3
  selector:
    matchLabels:
      app: comedy-backend
  template:
    metadata:
      labels:
        app: comedy-backend
    spec:
      containers:
      - name: backend
        image: comedy-app/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: supabase-url
        - name: SUPABASE_SERVICE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: supabase-service-key
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: comedy-backend-service
  namespace: comedy-discovery
spec:
  selector:
    app: comedy-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
